voteapp/urls.py
from django.urls import path
from voteapp import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('<user_username>/dashboard/', views.dashboard, name='dashboard'),
    path('<user_username>/vote/', views.vote_view, name='vote'),
    path('submit_vote/', views.submit_vote, name='submit_vote'),

    path('<user_username>/result/', views.result_view, name='result'),
    path('<user_username>/result/winners/', views.winners_view, name='winners'),
    path('<user_username>/profile/', views.profile_view, name='profile'),
    path('<user_username>/profile/edit_profile/', views.edit_profile_view, name='edit_profile'),
    path('<user_id>/profile/edit_profile/crop_image/', views.crop_image_view, name='crop_image'),

    path('<user_username>/profile/password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'), name='password_change_done'),
    path('<user_username>/profile/password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'), name='password_change'),
]

votesystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from accounts import views
from voteapp import views as view
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('voteapp.urls')),
    path('v/', include('voteapp.urls')),

    path('', view.index, name='index'),
    path('register/', views.registration_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset/password_reset_form.html'), name='reset_password'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset/password_reset_change_form.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'), name='password_reset_complete'),
    
]


urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/models.py
# accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import gettext_lazy as _
import uuid

class MyAccountManager(BaseUserManager):
    def create_user(self, email, username, password=None, matric_number=None, **extra_fields):
        if not email:
            raise ValueError(_('The Email field must be set'))
        if not username:
            raise ValueError(_('The Username field must be set'))
        email = self.normalize_email(email)
        user = self.model(email=email, username=username, matric_number=matric_number, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        return self.create_user(email, username, password, **extra_fields)

def get_profile_image_filepath(self, filename):
    return 'profile_images/' + str(self.pk) + '/profile_image.png'
    # return f'profile_images/{str(self.pk)}/{"profile_image.png"}'

def get_profile_image():
    return f'kscode/profile_image.png'

class Account(AbstractBaseUser, PermissionsMixin):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, unique=True, editable=False)
    email = models.EmailField(_('email address'), unique=True)
    username = models.CharField(_('username'), max_length=150, unique=True)
    matric_number = models.CharField(_('matric number'), max_length=20, blank=True, null=True)
    date_joined = models.DateTimeField(_('date joined'), auto_now_add=True)
    is_active = models.BooleanField(_('active'), default=True)
    is_staff = models.BooleanField(_('staff status'), default=False)
    
    profile_image = models.ImageField(upload_to=get_profile_image_filepath, default=get_profile_image, blank=True, null=True)
    
    is_student = models.BooleanField(default=False)
    is_candidate = models.BooleanField(default=False)

    
    objects = MyAccountManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
    
    def get_profile_image_filepath(self):
        return str(self.profile_image)[str(self.profile_image).index('profile_images/' + str(self.pk) + "/"):]
        # return str(self.profile_image)[str(self.profile_image).index(f'profile_images/{str(self.pk)}/'):]


    class Meta:
        verbose_name = _('account')
        verbose_name_plural = _('accounts')

    def __str__(self):
        return self.username

voteapp/models.py
from django.db import models
import uuid, random, string
from students.models import Student
from django.conf import settings

class Position(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=40, unique=True, blank=False, null=False)
    slug = models.SlugField(blank=True, null=True)
    total_vote = models.IntegerField(default=0)
    voters = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True)
    asociate_number = models.CharField(max_length=3, blank=True, null=True, default="--")

    def __str__(self):
        return self.title
     
class AspirantListStudent(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    matric_number = models.CharField(max_length=40, blank=False, null=False)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='aspirant', null=True, blank=True, default=None)
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='aspirant_student')
    position = models.ForeignKey(Position, on_delete=models.CASCADE, related_name="aspirant_position")
    total_vote = models.IntegerField(default=0)
    student_voters = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True)

    @property
    def percentage_vote(self):
        position_vote = self.position.total_vote
        item_votes = self.total_vote

        if (position_vote == 0):
            vote_in_percentage = 0
        else:
            vote_in_percentage = (item_votes/position_vote) * 100
        
        return vote_in_percentage
    
    def __str__(self):
        return self.student.fullname 

class Passcode(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, unique=True, editable=False)
    passcode = models.CharField(max_length=12, unique=True)
    is_used = models.BooleanField(default=False)
    user = models.OneToOneField(Student, blank=True, null=True, on_delete=models.SET_NULL, related_name="passcode_user")
    
    # def generate_passcode(self):
    #     characters = string.ascii_uppercase + string.digits
    #     passcode = ''.join(random.choice(characters) for _ in range(12))
    #     return passcode
    
    # def save(self, *args, **kwargs):
    #     self.passcode = self.generate_passcode()
    #     super().save(*args, **kwargs)

    def __str__(self):
        return self.passcode
 
class ElectionTime(models.Model):
    election_datetime = models.DateTimeField()
    duration = models.IntegerField()

    def __str__(self):
        return (f'Election on {self.election_datetime}')

accounts/forms.py
from django import forms
from django.db import transaction
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
from .models import Account
from students.models import Student
from voteapp.models import Passcode, Position, AspirantListStudent

class RegistrationForm(UserCreationForm):
    
    email = forms.EmailField(max_length=225, help_text='Required. Add a valid email address')
    matric_number = forms.CharField(max_length=20, required=False)
    role = forms.ChoiceField(choices=[('student', 'Student'), ('candidate', 'Candidate')])
    passcode = forms.CharField(max_length=12, required=False)
    position = forms.ModelChoiceField(queryset=Position.objects.all().order_by('title'), required=False)

    class Meta:
        model = Account
        fields = ('email', 'username', 'matric_number', 'password1', 'password2',)

    def clean_email(self):
        email = self.cleaned_data["email"].lower()
        if Account.objects.filter(email=email).exists():
            raise forms.ValidationError(f'Email {email} is already in use')
        return email
    
    def clean_username(self):
        username = self.cleaned_data["username"]
        if Account.objects.filter(username=username).exists():
            raise forms.ValidationError(f'Username {username} is already in use')
        return username

    
    def clean_matric_number(self):
        matric_number = self.cleaned_data["matric_number"]
        if Account.objects.filter(matric_number=matric_number).exists():
            raise forms.ValidationError(f'Matric number {matric_number} is already in use')
        try:
            student = Student.objects.get(matric_number=matric_number)
        except Student.DoesNotExist:
            raise forms.ValidationError(f'Matric number {matric_number} does not exist')
        return matric_number
            
    def clean_role(self):
        role = self.cleaned_data['role']
        if role == 'candidate':
            position = self.cleaned_data.get('position')
            matric_number = self.cleaned_data.get('matric_number')
            # Check if the candidate is already registered for the selected position
            if AspirantListStudent.objects.filter(position=position).exists():
                raise forms.ValidationError('Candidate is already registered for the selected position.')
            elif AspirantListStudent.objects.filter(student__matric_number=matric_number).exists():
                raise forms.ValidationError('Candidate is already registered for a position.')
        
        elif role != 'student':
            raise forms.ValidationError('Invalid role')
        return role

    def clean(self):
        cleaned_data = super().clean()
        role = cleaned_data.get('role')
        matric_number = cleaned_data.get('matric_number')
        position = cleaned_data.get('position')
        passcode = cleaned_data.get('passcode')

        if role == 'candidate':
            
            if Student.objects.filter(matric_number=matric_number, level=400).exists():
                pass
            elif Student.objects.filter(matric_number=matric_number, level=500).exists():
                pass
            else:
                raise forms.ValidationError('Only 400 levels students and above can register')

            passcode_objs = Passcode.objects.filter(passcode=passcode, is_used=False)
            if not passcode_objs.exists():
                raise forms.ValidationError('Invalid passcode or passcode already used')
            passcode_obj = passcode_objs.first()

            try:
                with transaction.atomic():
                    # Create the candidate
                    candidate = AspirantListStudent.objects.create(
                        matric_number=matric_number,
                        position=position,
                        student=Student.objects.get(matric_number=matric_number),
                    )
                    passcode_obj.is_used = True
                    passcode_obj.user = candidate.student  # Assuming candidate.user is the user associated with the candidate
                    passcode_obj.save()
                    
            except Exception as e:
                raise forms.ValidationError(f"Error creating candidate {str(e)}")

        return cleaned_data
    

class AccountAuthenicateForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    class Meta:
        model = Account
        fields = ('email', 'password')

    def clean(self):
        if self.is_valid():
            email = self.cleaned_data["email"]
            password = self.cleaned_data["password"]      
            if not authenticate(email=email, password=password):
                raise forms.ValidationError('Invalid login, please correct your credentials')
            

            
class AccountUpateForm(forms.ModelForm):

    class Meta:
        model = Account
        fields = ('email', 'username', 'profile_image')
    

    def clean_email(self):
        email = self.cleaned_data["email"].lower()
        try:
            account = Account.objects.exclude(pk=self.instance.pk).get(email=email)
        except Account.DoesNotExist:
            return email
        raise forms.ValidationError(f'Email {email} is already in use')

    def clean_username(self):
        username = self.cleaned_data["username"]
        try:
            account = Account.objects.exclude(pk=self.instance.pk).get(username=username)
        except Account.DoesNotExist:
            return username
        raise forms.ValidationError(f'Username {username} is already in use')
    
    def save(self, commit=True):
        account = super(AccountUpateForm, self).save(commit=False)
        account.username = self.cleaned_data['username']
        account.email = self.cleaned_data['email']
        # account.profile_image = self.cleaned_data['profile_image']
        if commit:
            account.save()
        return account
        

    
    
    

voteapp/templates/voteapp/edit_profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Edit Profile{% endblock title %}

{% block countdown %}
    {% include 'snippets/countdown_set.html' %}
{% endblock countdown %}


{% block content %}
<style type="text/css">
    #id_cropped_image_display {
        height: auto;
        object-fit: cover;
    }
    #id_profile_image_display1{
        width: 150px;
        height: 150px;
        object-fit: cover;
    }
    .image-container{
        position: relative;
    }
    #drag-content{
        width: 100%;
        height: 100%;
        border: 2px dashed #bbb5ff;
        background: #f7f8ff;
        padding: 1rem;
        cursor: pointer;
    }
    #drag-content.active{
        border: 2px solid #bbb5ff;
    }
</style>

<div class="container d-flex justify-content-center align-items-center">
    <div class="card mt-4 bg-light shadow-md p-md-3" style="width: 400px;">
        <div class="card-body">
            <p class="mb-3 fw-medium fs-5">Edit Profile</p>
            <div class="image-container mx-auto mb-3">
                <img class="d-block border shadow-lg border-dark rounded-circle img-fluid mx-auto profile-image" alt="Profile Image" id="id_profile_image_display1" src="{{ form.initial.profile_image.url }}">
                <div class="d-flex justify-content-center mt-2">
                    <button data-bs-toggle="modal" data-bs-target="#uploadModal" class="btn btn-primary">
                        Upload <i class="fa-solid fa-upload"></i>
                    </button>
                </div>
            </div>
            <form class="form-signin" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group mb-3">
                    <label for="id_input_email">Email</label>
                    <input class="form-control" type="text" id="id_input_email" name="email" value="{{form.initial.email}}" placeholder="Email address" required autofocus>
                </div>
                <div class="form-group mb-3">
                    <label for="id_input_username">Username</label>
                    <input class="form-control" type="text" id="id_input_username" name="username" value="{{form.initial.username}}" placeholder="Username" required autofocus>
                </div>
                {% for field in form %}
                    {% for error in field.errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}
                {% endfor %}
                {% if form.non_field_errors %}
                    <div style="color: red">
                        {% for error in form.non_field_errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
                <button class="btn btn-primary w-100" type="submit">Save</button>
            </form>
        </div>
    </div>
</div>

<!-- State 1: Upload Modal -->
<div class="modal fade" id="uploadModal" tabindex="-1" aria-labelledby="uploadModalLabel" aria-hidden="true" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-centered modal-screen" style="width: 400px;">
        <div class="modal-content">
            <div class="modal-body" id="drop-area">
                <h5 class="modal-title text-center" id="uploadModalLabel">Image Upload</h5>
                <label for="id_upload_profile_image" class="fs-5">
                    <input class="form-control" type="file" id="id_upload_profile_image" name="profile_image" onchange="fileSelected(event)" hidden>
                </label>

                <div id="drag-content" class="d-flex align-items-center justify-content-center">
                    <p class="text-center fs-6 mb-0">Drag and drop a picture, or click to select file</p>
                </div>
                <div class="mt-3 d-flex align-items-center justify-content-center">
                    <button type="button" class="btn btn-outline-secondary close-modal-button" data-bs-dismiss="modal">Close</button>
                </div>
            
            </div>
        </div>
    </div>
</div>


<!-- State 2: Cropper Modal -->
<div class="modal fade" id="cropperModal" tabindex="-1" aria-labelledby="cropperModalLabel" aria-hidden="true" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-centered modal-screen" style="width: 400px;">
        <div class="modal-content">
            <div class="modal-body">
                <h5 class="modal-title text-center mb-4" id="uploadModalLabel">Image Upload</h5>
                <div class="image-preview-container mx-auto mb-2 d-flex align-items-center justify-content-center">
                    <img class="d-block border shadow-lg border-dark img-fluid mx-auto profile-image" alt="Profile Image" id="id_cropped_image_display">
                </div>
                <div class="form-group d-flex justify-content-center my-5" id="change-image">
                    <button type="button" class="btn btn-primary" onclick="changeImage()">
                        Change Image
                        <i class="fa-solid fa-upload"></i>
                    </button>
                </div>

                <div class="mt-3 d-flex align-items-center justify-content-center gap-2">
                    <button type="button" class="btn btn-primary" id="save-crop">Save</button>
                    <button type="button" class="btn btn-outline-secondary close-modal-button" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>

<!--Modal for success or error-->
<div class="modal fade" id="responseModal" tabindex="-1" role="dialog" aria-labelledby="responseModalLabel" aria-hidden="true" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body" style="position: relative;">
                <p class="text-center mb-0" style="font-size: 3rem;">
                    <i id="responseIcon"></i>
                </p>
                <p id="responseMessage" class="text-center fw-medium text-uppercase"></p>            
                <div class="d-flex align-items-center justify-content-center">
                    <button type="button" class="btn btn-outline-secondary close-modal-message" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}


{% block userjs %}

   
<script>
    
    const dropArea = document.getElementById('drop-area')
    const dragContent = document.getElementById('drag-content')
    const dragText = document.querySelector('#drag-content p')
    var uploadImageDisplay = document.getElementById('id_cropped_image_display');
    let file; //this is a global variable and we'll use it inside mutliple functinos

    //If user Drag File Over DragArea
    dropArea.addEventListener("dragover", function(event){
        event.preventDefault();
        dragText.textContent = "Release to upload file";
        dragContent.classList.add('active');
    })

    //If user leave dragged File from DragArea
    dropArea.addEventListener("dragleave", ()=>{
        dragText.textContent = "Drag and drop a picture, or click to select file"
        dragContent.classList.remove('active');
    })

    // If user drop file on DragArea
    dropArea.addEventListener("drop", function(event) {
        event.preventDefault(); // Prevent the default behavior of the drop event
        var file = event.dataTransfer.files[0]

        if(file.type.startsWith("image/")){
            console.log("This is an image File")
            fileSelectedUser(file)
        }
        else{
            $('#uploadModal').modal('hide');
            $('#responseMessage').text(`This is not an image file!!!`).addClass('text-danger');
            $('#responseIcon').addClass('fa-solid fa-triangle-exclamation text-danger')
            $('#responseModal').modal('show');
        }
    });

    //If user click on the drag-area directly
    function fileSelected(event) {
        if (event.target.files) {
            var file = event.target.files[0];
            fileSelectedUser(file)
        }
    }

    function fileSelectedUser(file){
        var reader = new FileReader();
        reader.onload = function(e) {
            var image = e.target.result;
            uploadImageDisplay.src = image;
    
            cropper = new Cropper(uploadImageDisplay, {
                aspectRatio: 1/1,
                crop(event) {
                    setImageCropProperties(
                        image, event.detail.x, event.detail.y, 
                        event.detail.width, event.detail.height
                    );
                },
            });
        };
        
        reader.readAsDataURL(file); // Read the file as a data URL
        $('#uploadModal').modal('hide');
        $('#cropperModal').modal('show');
    }
    
    document.getElementById('drag-content').addEventListener('click', function() {
        document.getElementById('id_upload_profile_image').click();
    });

    document.querySelector('.close-modal-button').addEventListener('click', function() {
        dragContent.classList.remove('active');
        dragText.textContent = "Drag and drop a picture, or click to select file"
        //window.location.reload();
        $('#uploadModal').modal('hide');
        $('#cropperModal').modal('hide');
    });

    document.querySelector('.close-modal-message').addEventListener('click', function() {
        window.location.reload();
    });
    
    document.getElementById('change-image').addEventListener('click', function() {
        document.getElementById('id_upload_profile_image').click();
    });

    function changeImage() {
        uploadImageDisplay.src = "";

        if(cropper){
            cropper.destroy();
            cropper = null;
        }

        $('#cropperModal').modal('hide');
        $('#id_upload_profile_image').val(''); // Clear the file input field
        $('#uploadModal').modal('show');
    }
    
    var cropper, imageFile, base64ImageString, cropX, cropY, cropWidth, cropHeight

    function isImageSizeValid(image){
		var startIndex = image.indexOf("base64,") + 7
		var base64str = image.substr(startIndex)
		var decode = atob(base64str)
		if(decode.length >= "{{DATA_UPLOAD_MAX_MEMORY_SIZE}}"){
			return null
		}
		return base64str;
	}

    function setImageCropProperties(image, x, y, width, height){
		imageFile = image
		cropX = x
		cropY = y
		cropWidth = width
		cropHeight = height
	}

    function cropImage(image, x, y, width, height){

		base64ImageString = isImageSizeValid(image)
	
		if(base64ImageString != null){
			var requestData = {
				"csrfmiddlewaretoken": "{{ csrf_token }}",
				"image": base64ImageString,
				"cropX": cropX,
				"cropY": cropY,
				"cropWidth": cropWidth,
				"cropHeight": cropHeight
			};
			
            displayLoadingSpinner(true)
			
            // Using jQuery for AJAX request
			$.ajax({
				type: 'POST',
				dataType: "json",
				url: "{% url 'crop_image' user_id=form.initial.id %}",
				data: requestData,
				timeout: 10000,

				success: function(data) {
					if(data.result == "success"){
                        $('#cropperModal').modal('hide');
                        if (data.cropped_profile_image) {
                            $('#responseMessage').text('Profile image upload successfully').addClass('text-success');
                            $('#responseIcon').addClass('bi bi-patch-check-fill text-success')
                            $('#responseModal').modal('show');
                        }
					}
					else if(data.result == "error"){
                        $('#responseMessage').text(`${data.exception}`).addClass('text-danger');
                        $('#responseIcon').addClass('fa-solid fa-triangle-exclamation text-danger')
                        $('#responseModal').modal('show');
					}
				},
				error: function(data){
					console.error("ERROR...", data)
				},
				complete: function(data){
					displayLoadingSpinner(false)
				}
			});
		}
		else{
            $('#cropperModal').modal('hide');
            $('#responseMessage').text(`Upload an image smaller than 3 MB`).addClass('text-danger');
            $('#responseIcon').addClass('fa-solid fa-triangle-exclamation text-danger')
            $('#responseModal').modal('show');
		}
	}


    var saveCrop = document.getElementById("save-crop")
    saveCrop.addEventListener("click", function(event){
        console.log("Sending crop data for processing...")
        cropImage(
            imageFile, 
            cropX, 
            cropY, 
            cropWidth, 
            cropHeight
        )
    })
    
</script>

{% endblock userjs %}

voteapp/templates/voteapp/profile.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Profile{% endblock title %}

{% block countdown %}
    {% include 'snippets/countdown_set.html' %}
{% endblock countdown %}

{% block content %}

<style>
    #id_profile_image{
        width: 150px;
        height: 150px;
        object-fit: cover;
    }
    .image-container{
        position: relative;
    }
    .image-container i{
        height: 30px;
        width: 30px;
        background-color: #ff6b00;
        cursor: pointer;
        position: absolute;
        bottom: 10%;
        right: 30%;
    }
    .user-level-department{
        display: inline-flex;
        justify-content: space-between;
        list-style: none;
        font-size: 13px;
    }

    .img-fluid{
        width: 200px;
        height: auto;
        object-fit: cover;
    }
</style>

<div class="d-flex justify-content-center align-items-center">
    <div class="card mt-4 bg-light shadow-md p-md-3" style="width: 400px;">
        
        <div class="card-body">  

            <p class="mb-3 fw-semibold">My Profile</p>

            <div class="user-profile-bio bg-white shadow-sm py-3 px-3 rounded mb-4">
                
                <!-- Add a link around the profile image to trigger the modal -->
                <div class="image-container mx-auto mb-2 d-flex align-items-center justify-content-center">
                    <a data-bs-toggle="modal" data-bs-target="#exampleModal" type="button">
                        <img class="d-block border shadow-lg border-dark rounded-circle img-fluid mx-auto profile-image" alt="Profile Image" id="id_profile_image" src="{{ request.user.profile_image.url }}">
                    </a>
                </div>

                <div class="user-info">
                    <p class="text-center mb-1">
                        <span class="fw-semibold fs-5">{{request.user.student.fullname}}</span> <br>
                        <span class="fw-medium">{{request.user.student.matric_number}}</span>
                    </p>

                    <ul class="user-level-department w-100 ps-0 mb-0 fw-medium">
                        <li>◘
                            {% if request.user.is_candidate %}
                            Candidate
                            {% elif request.user.is_student %}
                                Student
                            {% else %}
                                Unknown
                            {% endif %}

                        </li>
                        <li>◘ {{request.user.student.department}}</li>
                        <li>◘ {{request.user.student.level}} Level</li>
                    </ul>
                </div>
            </div>
            
            <form autocomplete="off" id="profile-form">                
                <div class="form-group mb-3">
                    <label for="id_email">Username</label>
                    <input class="form-control" type="text" value="{{request.user.username}}" aria-label="Disabled input example" disabled readonly>
                </div>

                <div class="form-group mb-3">
                    <label for="id_email">Email</label>
                    <input class="form-control" type="text" value="{{request.user.email}}" aria-label="Disabled input example" disabled readonly>
                </div>
                             
                <a type="button" class="btn btn-primary btn-block w-100 mb-3" id="update-button" href="{% url 'edit_profile' user_username=request.user.username %}">Update Profile</a>  
                <a type="button" class="btn btn-secondary btn-block w-100 mb-3" id="change-password" href="{% url 'password_change' user_username=request.user.username %}">Change Password</a>  
            </form>
        </div>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-6" id="exampleModalLabel">{{request.user.student.fullname}} - Profile Image</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body d-flex align-items-center justify-content-center">
                <img class="img-fluid" src="{{ request.user.profile_image.url }}" alt="Profile Image">
            </div>
        </div>
    </div>
</div>

{% endblock content %}