voteapp/urls.py
from django.urls import path
from voteapp import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('<user_username>/dashboard/', views.dashboard, name='dashboard'),
    path('<user_username>/vote/', views.vote_view, name='vote'),
    path('submit_vote/', views.submit_vote, name='submit_vote'),

    path('<user_username>/result/', views.result_view, name='result'),
    path('<user_username>/result/winners/', views.winners_view, name='winners'),
    path('<user_username>/profile/', views.profile_view, name='profile'),
    path('<user_username>/profile/edit_profile/', views.edit_profile_view, name='edit_profile'),
    path('<user_id>/profile/edit_profile/crop_image/', views.crop_image_view, name='crop_image'),

    path('<user_username>/profile/password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'), name='password_change_done'),
    path('<user_username>/profile/password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'), name='password_change'),
]

votesystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from accounts import views
from voteapp import views as view
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('voteapp.urls')),
    path('v/', include('voteapp.urls')),

    path('', view.index, name='index'),
    path('register/', views.registration_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset/password_reset_form.html'), name='reset_password'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset/password_reset_change_form.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'), name='password_reset_complete'),
    
]


urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/models.py
# accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import gettext_lazy as _
import uuid

class MyAccountManager(BaseUserManager):
    def create_user(self, email, username, password=None, matric_number=None, **extra_fields):
        if not email:
            raise ValueError(_('The Email field must be set'))
        if not username:
            raise ValueError(_('The Username field must be set'))
        email = self.normalize_email(email)
        user = self.model(email=email, username=username, matric_number=matric_number, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        return self.create_user(email, username, password, **extra_fields)

def get_profile_image_filepath(self, filename):
    return 'profile_images/' + str(self.pk) + '/profile_image.png'
    # return f'profile_images/{str(self.pk)}/{"profile_image.png"}'

def get_profile_image():
    return f'kscode/profile_image.png'

class Account(AbstractBaseUser, PermissionsMixin):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, unique=True, editable=False)
    email = models.EmailField(_('email address'), unique=True)
    username = models.CharField(_('username'), max_length=150, unique=True)
    matric_number = models.CharField(_('matric number'), max_length=20, blank=True, null=True)
    date_joined = models.DateTimeField(_('date joined'), auto_now_add=True)
    is_active = models.BooleanField(_('active'), default=True)
    is_staff = models.BooleanField(_('staff status'), default=False)
    
    profile_image = models.ImageField(upload_to=get_profile_image_filepath, default=get_profile_image, blank=True, null=True)
    
    is_student = models.BooleanField(default=False)
    is_candidate = models.BooleanField(default=False)

    
    objects = MyAccountManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
    
    def get_profile_image_filepath(self):
        return str(self.profile_image)[str(self.profile_image).index('profile_images/' + str(self.pk) + "/"):]
        # return str(self.profile_image)[str(self.profile_image).index(f'profile_images/{str(self.pk)}/'):]


    class Meta:
        verbose_name = _('account')
        verbose_name_plural = _('accounts')

    def __str__(self):
        return self.username

accounts/forms.py
from django import forms
from django.db import transaction
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
from .models import Account
from students.models import Student
from voteapp.models import Passcode, Position, AspirantListStudent

class RegistrationForm(UserCreationForm):
    
    email = forms.EmailField(max_length=225, help_text='Required. Add a valid email address')
    matric_number = forms.CharField(max_length=20, required=False)
    role = forms.ChoiceField(choices=[('student', 'Student'), ('candidate', 'Candidate')])
    passcode = forms.CharField(max_length=12, required=False)
    position = forms.ModelChoiceField(queryset=Position.objects.all().order_by('title'), required=False)

    class Meta:
        model = Account
        fields = ('email', 'username', 'matric_number', 'password1', 'password2',)

    def clean_email(self):
        email = self.cleaned_data["email"].lower()
        if Account.objects.filter(email=email).exists():
            raise forms.ValidationError(f'Email {email} is already in use')
        return email
    
    def clean_username(self):
        username = self.cleaned_data["username"]
        if Account.objects.filter(username=username).exists():
            raise forms.ValidationError(f'Username {username} is already in use')
        return username

    
    def clean_matric_number(self):
        matric_number = self.cleaned_data["matric_number"]
        if Account.objects.filter(matric_number=matric_number).exists():
            raise forms.ValidationError(f'Matric number {matric_number} is already in use')
        try:
            student = Student.objects.get(matric_number=matric_number)
        except Student.DoesNotExist:
            raise forms.ValidationError(f'Matric number {matric_number} does not exist')
        return matric_number
            
    def clean_role(self):
        role = self.cleaned_data['role']
        if role == 'candidate':
            position = self.cleaned_data.get('position')
            matric_number = self.cleaned_data.get('matric_number')
            # Check if the candidate is already registered for the selected position
            if AspirantListStudent.objects.filter(position=position).exists():
                raise forms.ValidationError('Candidate is already registered for the selected position.')
            elif AspirantListStudent.objects.filter(student__matric_number=matric_number).exists():
                raise forms.ValidationError('Candidate is already registered for a position.')
        
        elif role != 'student':
            raise forms.ValidationError('Invalid role')
        return role

    def clean(self):
        cleaned_data = super().clean()
        role = cleaned_data.get('role')
        matric_number = cleaned_data.get('matric_number')
        position = cleaned_data.get('position')
        passcode = cleaned_data.get('passcode')

        if role == 'candidate':
            
            if Student.objects.filter(matric_number=matric_number, level=400).exists():
                pass
            elif Student.objects.filter(matric_number=matric_number, level=500).exists():
                pass
            else:
                raise forms.ValidationError('Only 400 levels students and above can register')

            passcode_objs = Passcode.objects.filter(passcode=passcode, is_used=False)
            if not passcode_objs.exists():
                raise forms.ValidationError('Invalid passcode or passcode already used')
            passcode_obj = passcode_objs.first()

            try:
                with transaction.atomic():
                    # Create the candidate
                    candidate = AspirantListStudent.objects.create(
                        matric_number=matric_number,
                        position=position,
                        student=Student.objects.get(matric_number=matric_number),
                    )
                    passcode_obj.is_used = True
                    passcode_obj.user = candidate.student  # Assuming candidate.user is the user associated with the candidate
                    passcode_obj.save()
                    
            except Exception as e:
                raise forms.ValidationError(f"Error creating candidate {str(e)}")

        return cleaned_data
    

class AccountAuthenicateForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    class Meta:
        model = Account
        fields = ('email', 'password')

    def clean(self):
        if self.is_valid():
            email = self.cleaned_data["email"]
            password = self.cleaned_data["password"]      
            if not authenticate(email=email, password=password):
                raise forms.ValidationError('Invalid login, please correct your credentials')
            

            
class AccountUpateForm(forms.ModelForm):

    class Meta:
        model = Account
        fields = ('email', 'username', 'profile_image')
    

    def clean_email(self):
        email = self.cleaned_data["email"].lower()
        try:
            account = Account.objects.exclude(pk=self.instance.pk).get(email=email)
        except Account.DoesNotExist:
            return email
        raise forms.ValidationError(f'Email {email} is already in use')

    def clean_username(self):
        username = self.cleaned_data["username"]
        try:
            account = Account.objects.exclude(pk=self.instance.pk).get(username=username)
        except Account.DoesNotExist:
            return username
        raise forms.ValidationError(f'Username {username} is already in use')
    
    def save(self, commit=True):
        account = super(AccountUpateForm, self).save(commit=False)
        account.username = self.cleaned_data['username']
        account.email = self.cleaned_data['email']
        # account.profile_image = self.cleaned_data['profile_image']
        if commit:
            account.save()
        return account
        

    
    
    

accounts/views.py
from django.shortcuts import render, redirect
from voteapp.models import Position
from accounts.forms import RegistrationForm, AccountAuthenicateForm
from accounts.models import Account
from students.models import Student
from voteapp.models import AspirantListStudent
from django.http import JsonResponse
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from login_required import login_not_required

# Create your views here.
@login_not_required
def registration_view(request):
    context = {}
    positions = Position.objects.all().order_by('asociate_number')
    context['position'] = positions

    user = request.user

    if user.is_authenticated:
        return redirect('dashboard', user_username=request.user.username)

    form = RegistrationForm()

    if request.method == 'POST' and request.is_ajax():
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_student = form.cleaned_data['role'] == 'student'
            user.is_candidate = form.cleaned_data['role'] == 'candidate'
            matric_number = form.cleaned_data.get('matric_number')
            user.save()

            if user.is_candidate:
                try:
                    aspirant = AspirantListStudent.objects.get(matric_number=matric_number)
                    if aspirant:
                        aspirant.user = user
                        aspirant.save()
                        print('successfully added the user')
                except AspirantListStudent.DoesNotExist:
                    print('error')
                    print(str(e))

            try:
                student = Student.objects.get(matric_number=matric_number)
                if student:
                    student.user = user
                    student.save()
            except Exception as e:
                print('error')
                print(str(e))
                return JsonResponse({'success': False, 'message': f'{str(e)}' })
            print('account created successfuly')
            return JsonResponse({'success': True, 'message': 'Registration successful', 'user_username': user.username})
        else:
            errors = form.errors
            non_field_errors = form.non_field_errors()
            # errors = dict(form.errors.items())
            return JsonResponse({'success': False, 'errors': errors, 'non_field_errors': non_field_errors, 'message': 'Registration failed. Please correct the errors.'})
    else:
        context['form'] = RegistrationForm()
        
    return render(request, 'accounts/register.html', context)

@login_not_required
def login_view(request):
    context = {}
    user = request.user

    if user.is_authenticated:
        return redirect('dashboard', user_username=request.user.username)
    
    form = AccountAuthenicateForm()

    if request.method == 'POST' and request.is_ajax():
        form = AccountAuthenicateForm(request.POST)
        if form.is_valid():
            email = request.POST.get('email')
            password = request.POST.get('password')
            user = authenticate(email=email, password=password)

            if user is not None:
                login(request, user)
                next_url = request.POST.get('next')
                if next_url:
                    print(next_url)
                    return JsonResponse({'success': True, 'message': 'Login successful', 'user_username': user.username, 'next': next_url})
                else:
                    return JsonResponse({'success': True, 'message': 'Login successful', 'user_username': user.username})
            else:
                return JsonResponse({'success': False, 'message': 'Invalid email or password'})
        else:
            errors = form.errors
            return JsonResponse({'success': False, 'message': 'Invalid form submission', 'errors': errors})
    else:
        context['form'] = AccountAuthenicateForm()
    return render(request, 'accounts/login.html', context)

# @login_required(login_url='login')
def logout_view(request):
    logout(request)
    return redirect("index")

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock title %}

{% block content %}

<div class="d-flex justify-content-center align-items-center">
    <div class="card form-layout mt-4 bg-light shadow-md p-md-3">
        <div class="card-body">
            <h1 class="mb-1 fs-4 fw-medium">Login to your account</h1>
            <hr class="mb-4">
            <form autocomplete="off" method="post" id="login-form">
                {% csrf_token %}
                <div class="form-group mb-3">
                    <label for="id_email">Email</label>
                    <input type="email" class="form-control" name="email" id="id_email" placeholder="Enter your emaill" required>
                </div>

                <div class="form-group mb-3">
                    <label for="id_password">Password</label>
                    <input type="password" class="form-control w-100" name="password" id="id_password" placeholder="Enter your password" required>
                </div>

                <input type="hidden" name="next" value="{% if request.GET.next %}{{ request.GET.next }}{% endif %}">

                <div class="form-group mb-3" id="error-message"></div>   
               
                <div class="float-left mb-3">
                    <a href="{% url 'reset_password' %}" class="text-reset"> Forgot Password? </a>
                </div>
                          
                <button type="submit" class="btn btn-primary btn-block w-100 mb-3" id="login-button">
                    <span class="spinner-border spinner-border-sm d-none" role="status" aria-hidden="true"></span>
                    <span class="loading-text d-none">Authenticating...</span>
                    <span class="original-text">Login</span>
                </button>  
                
                <div class="text-center">
                    <p class="text-reset">Dont't have an account <span> <a href="{% url 'register' %}"> Register </a> </span> </p> 
                </div>

            </form>
        </div>
    </div>
</div>

{% endblock content %}


{% block userjs %}

<script>
    $(document).ready(function() {
        $('#login-form').submit(function(e) {
            e.preventDefault(); 
            
            // Show loading text and spinner-border
            $('#login-button').addClass('disabled').attr('disabled', true);
            $('#login-button .loading-text').removeClass('d-none');
            $('#login-button .spinner-border').removeClass('d-none');
            $('#login-button .original-text').addClass('d-none');
            
            var formData = $(this).serialize();
    
            $.ajax({
                type: 'POST',
                url: "{% url 'login' %}",
                data: formData,
                dataType: 'json',
                success: function(response) {
                    if (response.success) {
                        if (response.next) {
                            window.location.href = response.next;
                        } else {
                            username = response.user_username
                            var url = "{% url 'dashboard' user_username='PLACEHOLDER_USER_USERNAME' %}".replace("PLACEHOLDER_USER_USERNAME", username)
                            window.location.href = url;
                        }
                    } else {
                        var errorMessage = '';
                        if (response.errors) {
                            for (var field in response.errors) {
                                errorMessage += '<div class="alert alert-warning alert-common-message">' + response.errors[field].join('<br>') + '</div>';
                                $('[data-field="' + field + '"]').addClass('error');
                            }
                        } else {
                            errorMessage = '<div class="alert alert-warning alert-common-message">' + response.message + '</div>';
                        }
    
                        $('#error-message').html(errorMessage).show(); // Show error messages
                        setTimeout(function() {
                            $('.alert-common-message').hide(); // Hide all alert messages after 5 seconds
                        }, 5000);
                    }
                },
                error: function(xhr, status, error) {
                    $('#message').text('Error: ' + error).css('color', 'red');
                },
                complete: function() {
                    // Hide spinner on register button
                    $('#login-button').removeClass('disabled').attr('disabled', false);
                    $('#login-button .loading-text').addClass('d-none');
                    $('#login-button .spinner-border').addClass('d-none');
                    $('#login-button .original-text').removeClass('d-none');
                }
            });
        });
    });
</script>
{% endblock userjs %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block title %}Registration{% endblock title %}

{% block content %}
<div class="container d-flex justify-content-center align-items-center">
    <div class="card form-layout mt-4 bg-light shadow-md p-md-3">
        <div class="card-body">
            <h1 class="mb-1 fs-4 fw-medium">Create your account</h1>
            <hr class="mb-4">
            <form autocomplete="off" method="post" id="registration-form" >
                
                {% csrf_token %}

                <div class="form-group mb-3">
                    <div id="message"></div>
                    <div id="error-message" style="display: none;"></div> 
                </div>  

                <div class="form-group mb-3">
                    <label for="id_role">Select Role:</label>
                    <select class="form-select" id="id_role" name="role" data-field="role" onchange="showPasscodeField()" autofocus>
                        <option value="" selected>---</option>
                        <option value="student">Student</option>
                        <option value="candidate">Candidate</option>
                    </select>
                </div>
                
                <div class="form-group mb-3 passcodeShowField" style="display: none;">
                    <label for="id_passcode">Passcode</label>
                    <input type="password" class="form-control" name="passcode" data-field="passcode" maxlength="12" id="id_passcode" placeholder="Enter passcode">
                </div>

                <div class="form-group mb-3 passcodeShowField" style="display: none;">
                    <label for="id_position">Select Position:</label>
                    <select class="form-select" id="id_position" data-field="position" name="position" required>     
                        <option value="" selected>------</option>
                        {% for position in position  %}
                        <option value="{{position.id}}">{{position.title}}</option>
                        {% endfor %}
                    </select>
                </div>
              
                <div class="form-group mb-3">
                    <label for="id_matric_number">Matric Number</label>
                    <input type="text" class="form-control" name="matric_number" data-field="matric_number" maxlength="20" required id="id_matric_number" placeholder="Enter your matric number">
                </div>
                
                <div class="form-group mb-3">
                    <label for="id_email">Email</label>
                    <input type="email" class="form-control" name="email" data-field="email" maxlength="225" required id="id_email" placeholder="Enter your email"> 
                </div>
                

                <div class="form-group mb-3">
                    <label for="id_username">Username</label>
                    <input type="text" class="form-control" name="username" data-field="username" maxlength="150" required id="id_username" placeholder="Enter your username">
                </div>

                <div class="form-group mb-3">
                    <label for="id_password1">Password</label>
                    <input type="password" class="form-control w-100" name="password1" data-field="password1" autocomplete="new-password" required id="id_password1" placeholder="Enter your password">
                </div>

                <div class="form-group mb-3">
                    <label for="id_password2">Password Confirmation</label>
                    <input type="password" class="form-control" name="password2"mdata-field="password2" autocomplete="new-password" required id="id_password2" class="form-control" placeholder="Confirm your password"> 
                </div>
                               
                <button type="submit" class="btn btn-primary btn-block w-100 mb-3" id="register-button">
                    <span class="spinner-border spinner-border-sm d-none" role="status" aria-hidden="true"></span>
                    <span class="loading-text d-none">Loading...</span>
                    <span class="original-text">Register</span>
                </button>    

                <div class="text-center">
                    <p class="text-reset mb-0">Already have an account <span> <a href="{% url 'login' %}"> Login </a> </span> </p> 
                </div>
            </form>

    </div>
</div>


<div class="modal fade" id="responseModal" tabindex="-1" role="dialog" aria-labelledby="responseModalLabel" aria-hidden="true" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body" style="position: relative;">
                {% comment %} <button type="button" class="btn-close close-modal-show" data-bs-dismiss="modal" aria-label="Close" style="float: right;"></button> {% endcomment %}
                <p class="text-center" style="font-size: 3rem;">
                    <i id="responseIcon"></i>
                </p>
                <p id="responseMessage" class="text-center fw-medium text-uppercase"></p>
            </div>
            <div class="modal-footer">
                {% comment %} <button type="button" class="btn btn-secondary close-modal-show" data-bs-dismiss="modal">Close</button> {% endcomment %}
                <a type="button" class="btn btn-secondary" href="{% url 'login' %}">Login</a>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block userjs %}
<script>
    function showPasscodeField() {
        var role = document.getElementById("id_role").value;
        var passcodeFields = document.getElementsByClassName("passcodeShowField");
    
        for (var i = 0; i < passcodeFields.length; i++) {
            passcodeFields[i].style.display = role === "candidate" ? "block" : "none";
        }
    }

    document.addEventListener('DOMContentLoaded', function() {
        var roleSelect = document.getElementById('id_role');
        var passcodeInput = document.getElementById('id_passcode');
        var positionSelect = document.getElementById('id_position');
    
        // Function to toggle the 'required' attribute based on role selection
        function toggleFieldsRequired() {
            if (roleSelect.value === 'candidate') {
                passcodeInput.setAttribute('required', 'required');
                positionSelect.setAttribute('required', 'required');
            } else {
                passcodeInput.removeAttribute('required');
                positionSelect.removeAttribute('required');
            }
        }
        roleSelect.addEventListener('change', toggleFieldsRequired);
        toggleFieldsRequired();
    });
    
    $(document).ready(function() {
        $('#registration-form').submit(function(e) {
            e.preventDefault(); 
            
            // Show loading text and spinner-border
            $('#register-button').addClass('disabled').attr('disabled', true);
            $('#register-button .loading-text').removeClass('d-none');
            $('#register-button .spinner-border').removeClass('d-none');
            $('#register-button .original-text').addClass('d-none');
            
            var formData = $(this).serialize();
    
            $.ajax({
                type: 'POST',
                url: "{% url 'register' %}",
                data: formData,
                dataType: 'json',
                success: function(response) {
                    if (response.success) {
                        
                        $('#responseMessage').text(response.message).addClass('text-success');
                        $('#responseIcon').addClass('bi bi-patch-check-fill text-success')
                        $('#responseModal').modal('show');
                        
                        
                        /*var messages = '<div class="alert alert-success alert-common-message">' + response.message + '</div>';
                        /$('#error-message').html('').hide();
                        $('#registration-form')[0].reset();

                        $('#message').html(messages).show();
                        setTimeout(function(){
                            window.location.href = "{% url 'login' %}"
                            $('.alert-common-message').hide();
                        }, 1000) 
                        */

                    } else {
                        var errorMessage = '';           
                        if (response.non_field_errors) {
                            errorMessage += '<div class="alert alert-warning alert-common-message">' + response.non_field_errors.join('<br>') + '</div>';
                        }
                        var errors = response.errors;
                        for (var field in errors) {
                            errorMessage += '<div class="alert alert-warning alert-common-message">' + errors[field].join('<br>') + '</div>';
                            $('[data-field="' + field + '"]').addClass('error');
                        }
    
                        $('#error-message').html(errorMessage).show(); // Show error messages
                        setTimeout(function() {
                            $('.alert-common-message').hide(); // Hide all alert messages after 5 seconds
                        }, 5000);
                    }
                },
                error: function(xhr, status, error) {
                    $('#message').text('Error: ' + error).css('color', 'red');
                },
                complete: function() {
                    // Hide spinner on register button
                    $('#register-button').removeClass('disabled').attr('disabled', false);
                    $('#register-button .loading-text').addClass('d-none');
                    $('#register-button .spinner-border').addClass('d-none');
                    $('#register-button .original-text').removeClass('d-none');
                }
            });
        });
    });
               
</script>
{% endblock userjs %}